apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: nginx-ns
  labels:
    app: nginx-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-server
  template:
    metadata:
      labels:
        app: nginx-server
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80


---

apiVersion: v1
kind: Service
metadata:
  name: nginx-server-svc
  namespace: nginx-ns
spec:
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30119
  selector:
    app: nginx-server
  type: NodePort


---
apiVersion: v1
kind: Namespace
metadata:
  name: nginx-ns
