apiVersion: apps/v1
kind: Deployment
metadata:
  name: zero-server
  namespace: zero-server
  labels:
    app: zero-server
spec:
  replicas: 3
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: zero-server
  template:
    metadata:
      labels:
        app: zero-server
    spec:
      imagePullSecrets:
      - name: my-aliyun
      containers:
      - name: zero-server
        image: registry.cn-hangzhou.aliyuncs.com/yeppy/zero:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8889
        resources:
          requests:
            cpu: 500m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 1024Mi
        volumeMounts:
        - name: timezone
          mountPath: /etc/localtime
      volumes:
        - name: timezone
          hostPath:
            path: /usr/share/zoneinfo/Asia/Shanghai

---

apiVersion: v1
kind: Service
metadata:
  name: zero-server-svc
  namespace: zero-server
spec:
  ports:
  - port: 8889
    targetPort: 8889
    nodePort: 30115
  selector:
    app: zero-server
  type: NodePort


